
Vagrant.configure("2") do |config|
   config.vm.define :web1UbuntuV2 do |node|
      node.vm.box = "bento/ubuntu-20.04"
      node.vm.network :private_network, ip: "192.168.100.8"
      node.vm.provision "shell", path: "script_2.sh"
      node.vm.hostname = "web1UbuntuV2"
   end
   config.vm.define :web2UbuntuV2 do |node|
      node.vm.box = "bento/ubuntu-20.04"
      node.vm.network :private_network, ip: "192.168.100.9"
      node.vm.provision "shell", path: "script_3.sh"
      node.vm.hostname = "web2UbuntuV2"
   end
   config.vm.define :haproxyUbuntuV2 do |node|
      node.vm.box = "bento/ubuntu-20.04"
      node.vm.network :private_network, ip: "192.168.100.10"
      node.vm.provision "shell", path: "script_1.sh"
      node.vm.hostname = "haproxyUbuntuV2"
   end
end